# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 04 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run the cronjob
      run: |
        python get_data.py
        git config --global user.name 'Christian Ruiz'
        git config --global user.email 'ruizcrp@users.noreply.github.com'
        git diff-index --quiet HEAD || (git commit -a -m'Automated Cronjob' --allow-empty && git push -f)

        

